name: Build pterodactyl-git-releases

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/build-pterodactyl-git-releases.yml'
      - 'pterodactyl-git-releases/**'
      - '!pterodactyl-git-releases/README.md'

env:
  DOCKER_OWNER: ${{ github.repository_owner }}
  DOCKER_CONTAINER: pterodactyl-git-releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Fix Docker environment variables
        run: |
          # Make lowercase
          echo "DOCKER_OWNER=$(echo $DOCKER_OWNER | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
          echo "DOCKER_CONTAINER=$(echo $DOCKER_CONTAINER | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Install Dependencies
        run: |
          apt-get update -y
          apt-get install -y lsof curl ca-certificates openssl git tar sqlite3 fontconfig libfreetype6 tzdata iproute2 libstdc++6 jq
 		      
      - name: Build and push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ${{ env.DOCKER_CONTAINER }}/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.DOCKER_OWNER }}/${{ env.DOCKER_CONTAINER }}:latest
